# python s1010frqListParadigms.py /Users/bogdan/elisp/_ghdata/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt > fiction.tokenized.shuffled_uk_paradigms.txt
# python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-errors.txt'

python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/corpus_all_tokenized_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/corpus_all_tokenized_uk-errors.txt'
python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/laws.txt.tokenized_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/laws.txt.tokenized_uk-errors.txt'
python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/wiki_dump.tokenized_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/wiki_dump.tokenized_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/wiki_dump.tokenized_uk-errors.txt'
python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/news.tokenized.shuffled_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/news.tokenized.shuffled_uk-errors.txt'
python s1010frqListParadigms2.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' > '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-paradigms.txt' 2>'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/ghdata/ukcorpus/fiction.tokenized.shuffled_uk-errors.txt'

